package com.art4l.dataconnector.module.dataconnector.domain.event;

// todo: this is a lot of repetition, same for the handlers
// we will likely never have any other events than "BEFORE_RECEIVE, ON_RECEIVE, AFTER_RECEIVE, BEFORE_REPLY, ON_REPLY, AFTER_REPLY" and can likely make these generic
// there should just be a way to describe a custom event that can be added just in case it's necessary
public enum CommandEventType {
    // Error
    ERROR,

    // Get Datafile
    BEFORE_RECEIVE_GET_DATAFILE_COMMAND,
    ON_RECEIVE_GET_DATAFILE_COMMAND,
    AFTER_RECEIVE_GET_DATAFILE_COMMAND,
    BEFORE_REPLY_GET_DATAFILE_COMMAND,
    ON_REPLY_GET_DATAFILE_COMMAND,
    AFTER_REPLY_GET_DATAFILE_COMMAND,

    
    // Put Datafile
    BEFORE_RECEIVE_PUT_DATAFILE_COMMAND,
    ON_RECEIVE_PUT_DATAFILE_COMMAND,
    AFTER_RECEIVE_PUT_DATAFILE_COMMAND,
    BEFORE_REPLY_PUT_DATAFILE_COMMAND,
    ON_REPLY_PUT_DATAFILE_COMMAND,
    AFTER_REPLY_PUT_DATAFILE_COMMAND,

    // Pick Login
    BEFORE_RECEIVE_LOGIN_COMMAND,
    ON_RECEIVE_LOGIN_COMMAND,
    AFTER_RECEIVE_LOGIN_COMMAND,
    BEFORE_REPLY_LOGIN_COMMAND,
    ON_REPLY_LOGIN_COMMAND,
    AFTER_REPLY_LOGIN_COMMAND,

    // Pick Exit
    BEFORE_RECEIVE_EXIT_COMMAND,
    ON_RECEIVE_EXIT_COMMAND,
    AFTER_RECEIVE_EXIT_COMMAND,
    BEFORE_REPLY_EXIT_COMMAND,
    ON_REPLY_EXIT_COMMAND,
    AFTER_REPLY_EXIT_COMMAND,

    //Kitting Area Selection
    BEFORE_RECEIVE_KITTING_AREA_COMMAND,
    ON_RECEIVE_KITTING_AREA_COMMAND,
    AFTER_RECEIVE_KITTING_AREA_COMMAND,
    BEFORE_REPLY_KITTING_AREA_COMMAND,
    ON_REPLY_KITTING_AREA_COMMAND,
    AFTER_REPLY_KITTING_AREA_COMMAND,

    //Scan Order Event
    BEFORE_RECEIVE_SCAN_ORDER_COMMAND,
    ON_RECEIVE_SCAN_ORDER_COMMAND,
    AFTER_RECEIVE_SCAN_ORDER_COMMAND,
    BEFORE_REPLY_SCAN_ORDER_COMMAND,
    ON_REPLY_SCAN_ORDER_COMMAND,
    AFTER_REPLY_SCAN_ORDER_COMMAND,
    
    //Data Log Event
    BEFORE_RECEIVE_LOG_DATA_COMMAND,
    ON_RECEIVE_LOG_DATA_COMMAND,
    AFTER_RECEIVE_LOG_DATA_COMMAND,
    BEFORE_REPLY_LOG_DATA_COMMAND,
    ON_REPLY_LOG_DATA_COMMAND,
    AFTER_REPLY_LOG_DATA_COMMAND,



    //General cleanup, for use during development
    BEFORE_RECEIVE_CLEANUP_COMMAND,
    ON_RECEIVE_CLEANUP_COMMAND,
    AFTER_RECEIVE_CLEANUP_COMMAND,
    BEFORE_REPLY_CLEANUP_COMMAND,
    ON_REPLY_CLEANUP_COMMAND,
    AFTER_REPLY_CLEANUP_COMMAND
}
